### ISSUE TITLE
[BUG] Terminating error occurs in the handling of a `PermissionError` produced by certain files in use

### ISSUE THREAD

**Issue by desseim** [rdiff-backup/rdiff-backup#619]
## Bug summary

An error occurs in the handling of a `PermissionError` produced by a Firefox lock file being in use.

## Version, Python, Operating System

```yaml
---
exec:
  api_version:
    actual: 0
    default: 200
    max: 201
    min: 200
  argv:
  - C:\Program Files\rdiff-backup\rdiff-backup.exe
  - info
  version: 2.1.0a1
python:
  executable: C:\Program Files\rdiff-backup\rdiff-backup.exe
  name: cpython
  version: 3.9.1
system:
  fs_encoding: utf-8
  platform: Windows-10-10.0.19041-SP0
...
```

## rdiff-backup call

```
rdiff-backup.exe -v5 backup --exclude-symbolic-links --include-globbing-filelist C:/filelist C:/ D:/
```

## What happened and what did you expect?

`rdiff-backup` threw a terminating `PermissionError`, aborting the backup and leaving the repository in an inconsistent state.

I expected the file to produce a non-terminating `ListError` and for the backup to continue, skipping this file.

## More information

Several other files being in use by the `System` process produce an `[Errno 13] Permission denied` error, but (I guess) the terminating `PermissionError` is caught and only a non-terminating `ListError` is eventually thrown and the backup continues afterwards.
But when backing up this `parent.lock` file being opened by `Firefox`, there seems to be an error while processing the `PermissionError`, aborting the script:
```
ListError: 'Users/TheUser/AppData/Local/Packages/MicrosoftWindows.Client.CBS_xxxxxxxxxxxxx/Settings/settings.dat.LOG2' [Errno 13] Permission denied: 
b'C:/Users/TheUser/AppData/Local/Packages/MicrosoftWindows.Client.CBS_xxxxxxxxxxxxx/Settings/settings.dat.LOG2'
ListError: 'Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock' [Errno 13] Permission denied: 
b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock'
Traceback (most recent call last):
  File "rdiff_backup\rpath.py", line 863, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: b'D:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 95, in _main_run
  File "rdiffbackup\actions\backup.py", line 143, in run
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 210, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 821, in fast_process_file
  File "rdiff_backup\rpath.py", line 869, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: b'D:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock'
[1300] Failed to execute script rdiff-backup
```
and:
```
Incrementing mirror file D:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/favicons.sqlite-wal
Exception '[Errno 13] Permission denied: b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock'' raised of class '<class 'PermissionError'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\Rdiff.py", line 40, in get_delta_sigrp_hash
  File "rdiff_backup\rpath.py", line 1100, in open

Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock
Incrementing mirror file D:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/xxxxxxxx.default-release/parent.lock
Cleaning up
```

In my environment, this happens consistently, always on the Firefox profile's `parent.lock` file.
When this file doesn't exist, the backup otherwise performs successfully to the end (despite several `ListError`s on other system files).

**Comment by desseim** [comment]
After exclude the incriminated `parent.lock` file from backups and test running it a few more times, the exact same error occurred on another file (namely `C:/Users/TheUser/AppData/Local/Packages/Microsoft.Windows.Search_xxxxxxxxxxxxx/AppData/Indexed DB/IndexedDB.edb`) with the exact same stack trace.

Note that in both  cases the issue is not systematically reproducible ; I guess it depends on whether the given file is being locked by another program at the time of backup or not.

I'll update the title of the issue accordingly.

**Comment by jmknoble** [comment]
I'm experiencing similar symptoms on a different platform with different circumstances:

- OS:  Linux
- Variant: Ubuntu 20.04.3 LTS (Focal Fossa)
- Subvariant: Ubuntu Budgie

Python and **rdiff-backup** version:

```bash
$ echo $SHELL
/bin/bash
$ type -a rdiff-backup
rdiff-backup is /bin/rdiff-backup
rdiff-backup is /usr/bin/rdiff-backup
rdiff-backup is /usr/bin/X11/rdiff-backup
$ type -a rdiff-backup |awk '{ system("/bin/realpath " $NF) }'
/usr/bin/rdiff-backup
/usr/bin/rdiff-backup
/usr/bin/rdiff-backup
$ head -n 1 /usr/bin/rdiff-backup 
#!/usr/bin/python3
$ /bin/realpath /usr/bin/python3
/usr/bin/python3.8
$ /usr/bin/python3.8 --version --version
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
$ /usr/bin/rdiff-backup --version
rdiff-backup 2.0.0
$ dpkg -S /usr/bin/rdiff-backup
rdiff-backup: /usr/bin/rdiff-backup
$ dpkg -l rdiff-backup
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  rdiff-backup   2.0.0-1      amd64        remote incremental backup
$ 
```

Backtrace:

```
PythonArgs: ['/bin/rdiff-backup', '-b', '-v5', '--terminal-verbosity', '4', '--exclude-other-filesystems', '--include-globbing-filelist', '/etc/backup/root-includes', '--print-statistics', '/', '/backup-local/leothboc/fs/root']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
     return function(*args)
   File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1410, in append
     return self.__class__(self.conn, self.base, self.index + ext)
   File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1082, in __init__
     self.setdata()
   File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1108, in setdata
     self.data = self.conn.rpath.make_file_dict(self.path)
   File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 386, in make_file_dict
     statblock = os.lstat(filename)
 PermissionError: [Errno 13] Permission denied: b'/tmp/.mount_KeePaswKQiNp'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 299, in get_indexpath
     return obj.get_safeindexpath()
 AttributeError: 'tuple' object has no attribute 'get_safeindexpath'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/bin/rdiff-backup", line 32, in <module>
     rdiff_backup.Main.error_check_Main(sys.argv[1:])
   File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
     Main(arglist)
   File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
     take_action(rps)
   File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
     Backup(rps[0], rps[1])
   File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 434, in Backup
     backup.Mirror_and_increment(rpin, rpout, incdir)
   File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
     DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
   File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 279, in patch_and_increment
     for diff in rorpiter.FillInIter(source_diffiter, dest_rpath):
   File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 202, in FillInIter
     for rp in rpiter:
   File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 114, in get_diffs
     for dest_sig in dest_sigiter:
   File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 196, in get_sigs
     for src_rorp, dest_rorp in cls.CCPP:
   File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 361, in __next__
     source_rorp, dest_rorp = next(self.iter)
   File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 95, in Collate2Iters
     relem1 = next(riter1)
   File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 376, in __next__
     next_elem = next(self.iter)
   File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 138, in Iterate_fast
     rpath, val = next(diryield_stack[-1])
   File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 121, in diryield
     new_rpath = robust.check_common_error(
   File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 44, in check_common_error
     return error_handler(exc, *args)
   File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 108, in error_handler
     log.ErrorLog.write_if_open("ListError", rpath.index + (filename, ),
   File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 313, in write_if_open
     cls.write(error_type, rp, exc)
   File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 284, in write
     logstr = cls.get_log_string(error_type, rp, exc)
   File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 322, in get_log_string
     return "%s: '%s' %s" % (error_type, cls.get_indexpath(rp), exc)
   File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 302, in get_indexpath
     return "/".join(obj)
 TypeError: sequence item 0: expected str instance, bytes found
```

The folder causing `PermissionError` is a temporary mountpoint created by running an [AppImage](https://appimage.org/) of [KeePassXC](https://keepassxc.org/) while a backup is in progress.  Not particularly surprising.

I will note that `/tmp/.mount_KeePas*` matches a recursive exclude pattern:

```bash
# cat /etc/backup/root-includes |egrep '^([-+] +)?/tmp'
- /tmp/**
# 
```
and so I would not expect that it would need to be `os.lstat()`-ed at all.

This is reproducible:

1. Run KeePassXC from its AppImage.
2. Verify that `/tmp/.mount_KeePas*` exists:

        # ls -laF /tmp |fgrep .mount_KeePas
        ls: cannot access '/tmp/.mount_KeePasKF5xkS': Permission denied
        d?????????  ? ?        ?           ?            ? .mount_KeePasKF5xkS/
        # cat /proc/mounts |fgrep /tmp/.mount
        KeePassXC-2.6.6-x86_64_4083925f87a12b7343aa0a7456c04c25.AppImage /tmp/.mount_KeePasKF5xkS fuse.KeePassXC-2.6.6-x86_64_4083925f87a12b7343aa0a7456c04c25.AppImage ro,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
        # 

3. Run **rdiff-backup**:

```bash
root@leothboc:~# /etc/backup/backup-unattended 
+ mount /backup-local
+ mkdir /backup-local/leothboc/.backup.lock.d
+ rdiff-backup -b -v5 --terminal-verbosity 4 --exclude-other-filesystems --include-globbing-filelist /etc/backup/root-includes --print-statistics / /backup-local/leothboc/fs/root
Using rdiff-backup version 2.0.0
	with cpython /usr/bin/python3 version 3.8.10
	on Linux-5.13.0-27-generic-x86_64-with-glibc2.29, fs encoding utf-8
Unable to import win32security module. Windows ACLs
not supported by filesystem at /
-----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Unable to import win32security module. Windows ACLs
not supported by filesystem at /backup-local/leothboc/fs/root/rdiff-backup-data/rdiff-backup.tmp.0
-----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           On
  Hard linking                                 On
  fsync() directories                          On
  Directory inc permissions                    On
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   Off
  Access control lists                         On
  Extended attributes                          On
  Windows access control lists                 Off
  Case sensitivity                             On
  Escape DOS devices                           Off
  Escape trailing spaces                       Off
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
Backup: escape_dos_devices = 0
Backup: escape_trailing_spaces = 0
Previous backup seems to have failed, regressing destination now.
Regressing to Sat Jan 29 13:27:47 2022
Reading globbing filelist /etc/backup/root-includes
Starting increment operation / to /backup-local/leothboc/fs/root
Exception 'sequence item 0: expected str instance, bytes found' raised of class '<class 'TypeError'>':
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 279, in patch_and_increment
    for diff in rorpiter.FillInIter(source_diffiter, dest_rpath):
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 202, in FillInIter
    for rp in rpiter:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 114, in get_diffs
    for dest_sig in dest_sigiter:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 196, in get_sigs
    for src_rorp, dest_rorp in cls.CCPP:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 361, in __next__
    source_rorp, dest_rorp = next(self.iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 95, in Collate2Iters
    relem1 = next(riter1)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 376, in __next__
    next_elem = next(self.iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 138, in Iterate_fast
    rpath, val = next(diryield_stack[-1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 121, in diryield
    new_rpath = robust.check_common_error(
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 44, in check_common_error
    return error_handler(exc, *args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 108, in error_handler
    log.ErrorLog.write_if_open("ListError", rpath.index + (filename, ),
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 313, in write_if_open
    cls.write(error_type, rp, exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 284, in write
    logstr = cls.get_log_string(error_type, rp, exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 322, in get_log_string
    return "%s: '%s' %s" % (error_type, cls.get_indexpath(rp), exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 302, in get_indexpath
    return "/".join(obj)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 35, in check_common_error
    return function(*args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1410, in append
    return self.__class__(self.conn, self.base, self.index + ext)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1082, in __init__
    self.setdata()
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 1108, in setdata
    self.data = self.conn.rpath.make_file_dict(self.path)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rpath.py", line 386, in make_file_dict
    statblock = os.lstat(filename)
PermissionError: [Errno 13] Permission denied: b'/tmp/.mount_KeePasKF5xkS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 299, in get_indexpath
    return obj.get_safeindexpath()
AttributeError: 'tuple' object has no attribute 'get_safeindexpath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 32, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 390, in error_check_Main
    Main(arglist)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 412, in Main
    take_action(rps)
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 348, in take_action
    Backup(rps[0], rps[1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/Main.py", line 434, in Backup
    backup.Mirror_and_increment(rpin, rpout, incdir)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 55, in Mirror_and_increment
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 279, in patch_and_increment
    for diff in rorpiter.FillInIter(source_diffiter, dest_rpath):
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 202, in FillInIter
    for rp in rpiter:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 114, in get_diffs
    for dest_sig in dest_sigiter:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 196, in get_sigs
    for src_rorp, dest_rorp in cls.CCPP:
  File "/usr/lib/python3/dist-packages/rdiff_backup/backup.py", line 361, in __next__
    source_rorp, dest_rorp = next(self.iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 95, in Collate2Iters
    relem1 = next(riter1)
  File "/usr/lib/python3/dist-packages/rdiff_backup/rorpiter.py", line 376, in __next__
    next_elem = next(self.iter)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 138, in Iterate_fast
    rpath, val = next(diryield_stack[-1])
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 121, in diryield
    new_rpath = robust.check_common_error(
  File "/usr/lib/python3/dist-packages/rdiff_backup/robust.py", line 44, in check_common_error
    return error_handler(exc, *args)
  File "/usr/lib/python3/dist-packages/rdiff_backup/selection.py", line 108, in error_handler
    log.ErrorLog.write_if_open("ListError", rpath.index + (filename, ),
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 313, in write_if_open
    cls.write(error_type, rp, exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 284, in write
    logstr = cls.get_log_string(error_type, rp, exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 322, in get_log_string
    return "%s: '%s' %s" % (error_type, cls.get_indexpath(rp), exc)
  File "/usr/lib/python3/dist-packages/rdiff_backup/log.py", line 302, in get_indexpath
    return "/".join(obj)
TypeError: sequence item 0: expected str instance, bytes found
+ rmdir /backup-local/leothboc/.backup.lock.d
+ sync
+ umount -r /backup-local
root@leothboc:~# 
```

**Comment by ericzolf** [comment]
@jmknoble I suspect that your issue is a different one, and that it should have been fixed a long time ago. If you can still reproduce it with the [latest alpha release](https://github.com/rdiff-backup/rdiff-backup/releases/tag/v2.1.1a0), please create a separate issue. Thanks (and sorry for the time it took me to react).

**Comment by ericzolf** [comment]
I tried to reproduce your error but it doesn't seem to be possible, but I have a few more things to try.

For now, just my notes:

1. in one terminal, call python and cut & paste (keep the window open):

```python
import win32con, win32file, pywintypes
LOCK_EX = win32con.LOCKFILE_EXCLUSIVE_LOCK
LOCK_SH = 0 # the default
LOCK_NB = win32con.LOCKFILE_FAIL_IMMEDIATELY
__overlapped = pywintypes.OVERLAPPED(  )

def lock(file, flags):
    hfile = win32file._get_osfhandle(file.fileno(  ))
    win32file.LockFileEx(hfile, flags, 0, 0xffff0000, __overlapped)

def unlock(file):
    hfile = win32file._get_osfhandle(file.fileno(  ))
    win32file.UnlockFileEx(hfile, 0, 0xffff0000, __overlapped)

fp = open("/temp/from/test.txt", "w+")
lock(fp, LOCK_EX)
fp.write("lock test")   # optional, just to have something in the file
```
2. then, in another terminal, call: `"build\rdiff-backup-2.1.1a1.dev25+g8927c91-64\rdiff-backup.exe" -v5 backup \temp\from \temp\bak`, output is (notice that the next file is properly backed-up):
```
NOTE: Starting mirror from source path /temp/from to destination path /temp/bak 
* Processing file .
* Processing file test.txt
* Exception '[Errno 13] Permission denied' raised of class '<class 'PermissionEr
ror'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 1584, in copy
  File "rdiff_backup\rpath.py", line 1618, in copy_reg_file
  File "rdiff_backup\rpath.py", line 1161, in write_from_fileobj
  File "rdiff_backup\rpath.py", line 1535, in copyfileobj
  File "rdiff_backup\rpath.py", line 1512, in read
  File "rdiff_backup\hash.py", line 43, in read

WARNING: UpdateError: 'test.txt' [Errno 13] Permission denied
* Processing file test2.txt
* Cleaning up
```
@desseim if you could try to reproduce your issue with my steps and your version of rdiff-backup, respectively with your setup and the [latest alpha version of rdiff-backup 2.1.1a0](https://github.com/rdiff-backup/rdiff-backup/releases/tag/v2.1.1a0), that would be much appreciated. Before I can fix anything, I need a reproducer. This said, I might already have fixed the issue, as I fixed a similar behavior.

**Comment by desseim** [comment]
Thanks for investigating.

I reproduced your test file structure, ran the locking code in a python interpreter, and ran the backup command with rdiff-backup `v2.1.1a0`; see the log below.

Unfortunately, `v2.1.1a0` is prone to the bug reported in #686, so I'm afraid it doesn't give much information wrt the bug originally reported in this issue :confused: 

```console
> "C:\Program Files\rdiff-backup-2.1.1a0\rdiff-backup.exe" -v5 backup \temp\from \temp\bak
Traceback (most recent call last):
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 1578, in copy
  File "rdiff_backup\rpath.py", line 1612, in copy_reg_file
  File "rdiff_backup\rpath.py", line 1155, in write_from_fileobj
  File "rdiff_backup\rpath.py", line 1529, in copyfileobj
  File "rdiff_backup\rpath.py", line 1506, in read
  File "rdiff_backup\hash.py", line 43, in read
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 37, in main_run_and_exit
  File "rdiff_backup\Main.py", line 103, in _main_run
  File "rdiffbackup\actions\backup.py", line 161, in run
  File "rdiff_backup\backup.py", line 39, in mirror_compat200
  File "rdiff_backup\backup.py", line 198, in patch
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 601, in fast_process_file
  File "rdiff_backup\backup.py", line 656, in _patch_to_temp
  File "rdiff_backup\backup.py", line 702, in _patch_snapshot_to_temp
  File "rdiff_backup\robust.py", line 102, in check_common_error
  File "rdiff_backup\robust.py", line 68, in error_handler
  File "rdiff_backup\log.py", line 352, in write_if_open
AttributeError: type object 'ErrorLog' has no attribute 'write'
[15132] Failed to execute script 'rdiff-backup' due to unhandled exception!
* Using repository '/temp/bak'
* Hardlinks disabled by default on Windows
* Unable to import module (py)xattr. Extended attributes not supported on filesystem at path /temp/from
* Unable to import module posix1e from pylibacl package. POSIX ACLs not supported on filesystem at path /temp/from
* -----------------------------------------------------------------
Detected abilities for source (read only) file system:
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 On
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
* Directories on file system at path /temp/bak/rdiff-backup-data/rdiff-backup.tmp.0 are not fsyncable. Assuming it's unnecessary.
* Unable to import module (py)xattr. Extended attributes not supported on filesystem at path /temp/bak/rdiff-backup-data/rdiff-backup.tmp.0
* Unable to import module posix1e from pylibacl package. POSIX ACLs not supported on filesystem at path /temp/bak/rdiff-backup-data/rdiff-backup.tmp.0
* Unable to load a Windows ACL. Windows ACLs not supported by filesystem at path /temp/bak/rdiff-backup-data/rdiff-backup.tmp.0
* -----------------------------------------------------------------
Detected abilities for destination (read/write) file system:
  Ownership changing                           Off
  Hard linking                                 On
  fsync() directories                          Off
  Directory inc permissions                    Off
  High-bit permissions                         On
  Symlink permissions                          Off
  Extended filenames                           On
  Windows reserved filenames                   On
  Access control lists                         Off
  Extended attributes                          Off
  Windows access control lists                 Off
  Case sensitivity                             Off
  Escape DOS devices                           On
  Escape trailing spaces                       On
  Mac OS X style resource forks                Off
  Mac OS X Finder information                  Off
-----------------------------------------------------------------
* Backup: escape_dos_devices = False
* Backup: escape_trailing_spaces = False
* Enabled use_compatible_timestamps
NOTE: Symbolic links excluded by default on Windows
* Given repository doesn't need to be regressed
NOTE: Starting mirror from source path /temp/from to destination path /temp/bak
* Processing file .
* Processing file test.txt
* Exception '[Errno 13] Permission denied' raised of class '<class 'PermissionError'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\rpath.py", line 1578, in copy
  File "rdiff_backup\rpath.py", line 1612, in copy_reg_file
  File "rdiff_backup\rpath.py", line 1155, in write_from_fileobj
  File "rdiff_backup\rpath.py", line 1529, in copyfileobj
  File "rdiff_backup\rpath.py", line 1506, in read
  File "rdiff_backup\hash.py", line 43, in read

* Cleaning up
```

**Comment by ericzolf** [comment]
OK, let's wait until I've released the next version, it should be a beta, once PR #713 has been reviewed and merged.

**Comment by ericzolf** [comment]
If you could try the new beta version v2.1.2b1 on your issue, I'd appreciate a lot.

**Comment by desseim** [comment]
Thank you for all the work towards the coming release, it's very much appreciated.

I'll gladly check again with `v2.1.2b1`, but it looks like the Windows build was broken and removed.
Do I assume correctly that a new Windows build will soon be re-uploaded?

**Comment by ericzolf** [comment]
Yes, sorry, I already found out that it's most probably due to the newer version of PyInstaller :cry:

**Comment by desseim** [comment]
I still encounter this error during a full system backup with `v2.1.2b2`.

First of all, I obtained the same result as you running [your example](https://github.com/rdiff-backup/rdiff-backup/issues/619#issuecomment-1226805589), with `v2.1.2b2` but *with `v2.1.0a1` as well*.
So just locking one file and backing it up doesn't reproduce this error.

I tried locking and backing up a 1000 text files, either in a flat hierarchy or each in their own directory, but this too executed successfully.

I only manage to reproduce this behavior by running a full system backup while having a Firefox window opened by a logged-in user (in this particular example, but it also happens with other files locked by other programs).

As for the error, I can confirm as I [reported earlier](https://github.com/rdiff-backup/rdiff-backup/issues/619#issuecomment-907436869) that the backup runs successfully when its scope is narrowed down to the problematic file/directory, although it fails on the same file/directory within a full system backup.
Note that the backup reports *a lot* of `ListError`s (`[WinError 5] Access`, `[Errno 13] Permission denied`) or `Exception '[WinError 5] Access is denied` but they are caught and the script proceeds further; the `parent.lock` file though causes a `PermissionError: [WinError 32]` and an unhandled exception which stops the backup script.

Looking at the output (see below) it seems to me that the unhandled exception is thrown trying to delete the backup *destination* file (and not accessing the source one). The backup *destination* file is the one being unaccessible because in use (by rdiff-backup I suppose, what else?).
There also is some further "processing" output after the uncaught exception, but relating to alphabetically "previous" files.
I don't know the codebase nor whether the script spawns multiple threads, and the out-of-order output might be an artifact of the script output mechanism, but it looks a bit like a potential race condition.

This could also explain why it only reproduces when running bigger-scoped backups.

See the logs (I truncated most unrelated lines but left a few relevant to the points discussed above):

With `v2.1.0a1`, verbose option `-v5` (same result as [initial post](https://github.com/rdiff-backup/rdiff-backup/issues/619#issue-981428579), but I re-ran it for direct comparison with the latest executable version):
```console
#...
ListError: 'Users/TheUser/AppData/Local/Temp/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.tmp' [Errno 13] Permission denied: b'C:/Users/TheUser/AppData/Local/Temp/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.tmp'
ListError: 'Users/TheUser/AppData/Local/Temp/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy.tmp' [Errno 13] Permission denied: b'C:/Users/TheUser/AppData/Local/Temp/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy.tmp'
ListError: 'Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock' [Errno 13] Permission denied: 
b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
Traceback (most recent call last):
  File "rdiff_backup\rpath.py", line 863, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
b'X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiff_backup\Main.py", line 38, in main_run_and_exit
  File "rdiff_backup\Main.py", line 95, in _main_run
  File "rdiffbackup\actions\backup.py", line 143, in run
  File "rdiff_backup\backup.py", line 55, in Mirror_and_increment
  File "rdiff_backup\backup.py", line 210, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 821, in fast_process_file
  File "rdiff_backup\rpath.py", line 869, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
b'X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
[17624] Failed to execute script rdiff-backup
Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/SiteSecurityServiceState.txt
Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/bookmarkbackups
Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/bookmarkbackups
#...
Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/favicons.sqlite-wal
Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/favicons.sqlite-wal
Exception '[Errno 13] Permission denied: b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'' raised of class '<class 'PermissionError'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\Rdiff.py", line 40, in get_delta_sigrp_hash
  File "rdiff_backup\rpath.py", line 1100, in open

Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock
Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock
Cleaning up
```

With `v2.1.2b2`, `backup` from `C:/` to `X:/Backup`, verbose option `-v5`:
```console
#...
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/C...
* Processing changed file Users/TheUser/AppData/Roaming/C...
WARNING: ListError: 'Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock' [Errno 13] Permission denied: 
b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
Traceback (most recent call last):
  File "rdiff_backup\rpath.py", line 905, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
b'X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiffbackup\run.py", line 92, in main_run
  File "rdiffbackup\actions\backup.py", line 154, in run
  File "rdiff_backup\backup.py", line 53, in mirror_and_increment_compat200
  File "rdiff_backup\backup.py", line 210, in patch_and_increment
  File "rdiff_backup\rorpiter.py", line 146, in __call__
  File "rdiff_backup\backup.py", line 818, in fast_process_file
  File "rdiff_backup\rpath.py", line 911, in delete
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 
b'X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'
[12896] Failed to execute script 'rdiff-backup' due to unhandled exception!
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/C...
* Processing changed file Users/TheUser/AppData/Roaming/C...
#...
* Processing changed file X:/Backup/Users/TheUser/AppData/Roaming/Microsoft
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Microsoft
#...
* Processing changed file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla
* Processing changed file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox
* Processing changed file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles
* Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release
* Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/AlternateServices.txt
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/AlternateServices.txt
#...
* Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/favicons.sqlite-wal
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/favicons.sqlite-wal
* Exception '[Errno 13] Permission denied: b'C:/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock'' raised of class '<class 'PermissionError'>':
  File "rdiff_backup\robust.py", line 94, in check_common_error
  File "rdiff_backup\Rdiff.py", line 38, in get_delta_sigrp_hash
  File "rdiff_backup\rpath.py", line 1138, in open

* Processing changed file Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock
* Incrementing mirror file X:/Backup/Users/TheUser/AppData/Roaming/Mozilla/Firefox/Profiles/zzzzzzzz.default-release/parent.lock
* Cleaning up
```

Running `rdiff-backup verify` with `v2.1.2b2` after the above `backup` run:
```console
WARNING: Two different times for current mirror found
 
Traceback (most recent call last):
  File "rdiff-backup", line 32, in <module>
  File "rdiffbackup\run.py", line 92, in main_run
  File "rdiffbackup\actions\verify.py", line 100, in run
  File "rdiff_backup\compare.py", line 218, in Verify
  File "rdiffbackup\meta\__init__.py", line 61, in iterate
  File "rdiffbackup\meta\__init__.py", line 75, in _iterate_records
  File "rdiffbackup\meta\__init__.py", line 139, in _get_next_pos
  File "gzip.py", line 301, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 479, in read
  File "gzip.py", line 523, in _read_eof
  File "gzip.py", line 425, in _read_exact
EOFError: Compressed file ended before the end-of-stream marker was reached
[11620] Failed to execute script 'rdiff-backup' due to unhandled exception!
```

**Comment by ericzolf** [comment]
Thanks for checking again, I'll have then a deeper look. I'd definitely like to have it fixed for 2.2.0 (hence the milestone).

**Comment by ericzolf** [comment]
OK, got it reproduced (slightly different output because I use cmd where you seem to use PowerShell):

```
> rdiff-backup -v5 backup --exclude ignorecase:/users/vagrant/appdata/local \Users\vagrant\AppData \temp\bak
[...]
* Incrementing mirror file /temp/bak/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/favicons.sqlite-wal
* Exception '[Errno 13] Permission denied: b'/Users/vagrant/AppData/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'' raised of class '<class 'PermissionError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rd
iff_backup\robust.py", line 94, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rd
iff_backup\rpath.py", line 1138, in open
    return open(self.path, mode)

WARNING: ListError: '/Users/vagrant/AppData/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock' [Errno 13] Permission denied: b'/Users/vagrant/AppData/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'

* Processing changed file Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock
* Incrementing mirror file /temp/bak/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock
* Processing changed file Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/places.sqlite-wal
```

But then the file isn't being backed-up and the repository isn't corrupted. Could the difference be due to a different shell? Could you try under plain cmd.exe?

**Comment by ericzolf** [comment]
OK, got it, I think. The file `parent.lock` exists also if Firefox isn't running, but then it isn't locked and can be backed-up. If I then restart Firefox and try again a backup, I get:

```
* Incrementing mirror file /temp/bak3/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.
default-release/favicons.sqlite-wal
* Exception '[Errno 13] Permission denied: b'/Users/vagrant/AppData/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'' raised of class '<class 'PermissionError'>':
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\robust.py", line 94, in check_common_error
    return function(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\Rdiff.py", line 38, in get_delta_sigrp_hash
    rp_signature.open("rb"), hash.FileWrapper(rp_new.open("rb")))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\rpath.py", line 1138, in open
    return open(self.path, mode)

WARNING: ListError: 'Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock' [Errno 13] Permission denied: b'/Users/vagrant/AppData/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'
* Processing changed file Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock
* Incrementing mirror file /temp/bak3/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock
* Cleaning up
Traceback (most recent call last):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\rpath.py", line 905, in delete
    self.conn.os.unlink(self.path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: b'/temp/bak3/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vagrant\Develop\rdiff-backup\build\scripts-3.10\rdiff-backup", line 32, in <module>
    sys.exit(rdiffbackup.run.main_run(sys.argv[1:]))
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\run.py", line 92, in main_run
    ret_val |= conn_act.run()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\actions\backup.py", line 154, in run
    backup.mirror_and_increment_compat200(
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\backup.py", line 53, in mirror_and_increment_compat200
    DestS.patch_and_increment(dest_rpath, source_diffiter, inc_rpath)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\backup.py", line 210, in patch_and_increment
    ITR(diff.index, diff)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\rorpiter.py", line 146, in __call__
    last_branch.fast_process_file(*args)
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\backup.py", line 818, in fast_process_file
    mirror_rp.delete()
  File "C:\Users\vagrant\Develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\rpath.py", line 911, in delete
    self.conn.os.unlink(self.path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: b'/temp/bak3/Roaming/Mozilla/Firefox/Profiles/p7rmw06c.default-release/parent.lock'
```
And _then_ the backup is interrupted and `rdiff-backup verify` complains about 7 corrupted files (regression worked though, and after that verfiication was successful).

**Comment by ericzolf** [comment]
Windows is strange:

```
>openfiles /query /fo csv | find /I "parent.lock"
"768","firefox.exe","C:\Users\vagrant\AppData\Roaming\Mozilla\Firefox\Profiles\p7rmw06c.default-release\parent.lock"
"928","python.exe","C:\temp\bak\Roaming\Mozilla\Firefox\Profiles\p7rmw06c.default-release\parent.lock"
```

Meaning: rdiff-backup manages to copy and take over the locking on the file, but then fails to remove it (it probably tries to do so because it thinks the source file couldn't be copied, due to the first permission denied, and hence it needs to disappear from the repo, hence the unlink call, which leads to the 2nd permission denied). The first one is caught, but the 2nd one is... unexpected.

This is weirder als weird, I'm not sure yet how to handle this properly. I think the best way would be to avoid taking over the lock, or removing it, but as I don't understand how it appears, that's difficult.

**Comment by ericzolf** [comment]
Sorry for the noise, still using this issue as notepad...

I reduced the command to `python -m pdb build\scripts-3.10\rdiff-backup -v5 --api-version 201 backup --include **/parent.loc
k --exclude **/*  \users\vagrant\AppData\Roaming\Mozilla\Firefox\Profiles\f853zjpw.default-release \temp\bak` in order to have only `parent.lock` left to consider, making debugging much easier.

Now "drilling" through the code, while checking with `openfiles` at which point the lock goes from one file/process to the next:

```
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_repo_shadow.py:118
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_dir_shadow.py:107
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_repo_shadow.py:182
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_repo_shadow.py:221
> c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiff_backup\rpath.py(1138)open()-><_io.Buffered.../parent.lock'>   # this is where the locking happens...
```

So the issue isn't that the file is locked, it is simply locked because the file is opened, it's because the file doesn't get closed (that makes more sense), further drilling hence:

```
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_repo_shadow.py:185  # this is where the exception happens
b c:\users\vagrant\develop\rdiff-backup\build\lib.win-amd64-cpython-310\rdiffbackup\locations\_dir_shadow.py:124  # Permission denied on _source_ parent,lock
```
And finally it was the `Rdiff.get_delta_sigrp_hash` function which didn't close the destination file when the source file wasn't readable. I'm still trying to write a test for this, but basically the fix is written.

**Comment by desseim** [comment]
Your analysis makes complete sense with regards to my understanding of the issue.

I'll try again once new release artifacts are out, it should simplify my exclude list quite significantly :)
Thanks a lot for the dedicated debugging!

I also put in a couple comments on the PR, but I understand they come in late.
